name: linters

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  flake8:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install poetry
        run: python -m pip install --upgrade pip wheel setuptools
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Analysing the code with flake8
        run: |
          python -m flake8 .
  pylint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install poetry
        run: python -m pip install --upgrade pip wheel setuptools
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Analysing the code with pylint
        run: |
          pylint pyswaggerclient
  safety:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install poetry
        run: python -m pip install --upgrade pip wheel setuptools
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Analysing the dependencies with safety
        run: |
          echo 'Ignore 70612 / CVE-2019-8341, Jinja2 is a safety dep, not ours'
          python -m safety check --ignore 70612
