name: linters

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      - name: Install dependencies
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install --no-cache-dir -r requirements-dev.txt
  flake8:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
      - name: Analysing the code with flake8
        run: |
          python -m flake8 .
  pylint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
      - name: Analysing the code with pylint
        run: |
          pylint pyswaggerclient
  safety:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
      - name: Analysing the dependencies with safety
        run: |
          echo 'Ignore 70612 / CVE-2019-8341, Jinja2 is a safety dep, not ours'
          python -m safety check --ignore 70612